# Generated by Django 4.1.7 on 2023-03-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp01', '0003_usuario_tipo_user_alter_usuario_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
