# Generated by Django 4.1.7 on 2023-03-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp01', '0004_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.CharField(max_length=20, null=True)),
                ('descricao', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
