# Generated by Django 4.1.7 on 2023-03-03 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp01', '0005_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_valor', models.DateTimeField(auto_now=True)),
                ('cod_valor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meuapp01.produto')),
            ],
        ),
    ]
